In [2]:
import numpy as np
arr1 = np.array([[1,2],[3,4]])
print(arr1,"\n")

arr2 = np.array([[5,6],[7,8]])
print(arr2,"\n")

arr_sum =arr1 + arr2
print(arr_sum)

[[1 2]
 [3 4]] 

[[5 6]
 [7 8]] 

[[ 6  8]
 [10 12]]


In [3]:
arr_dot = np.dot(arr1,arr2)
print(arr_dot)

[[19 22]
 [43 50]]


In [4]:
arr_elementwise_multiplication = arr1 * arr2
print(arr_elementwise_multiplication)

[[ 5 12]
 [21 32]]


In [5]:
arr_matrix_multiplication = arr1 @ arr2
print(arr_matrix_multiplication)

[[19 22]
 [43 50]]
